/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gkform;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class RegistrationPage extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationPage
     */
    public RegistrationPage() {
        initComponents();
          jButton2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        other = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        bvn = new javax.swing.JTextField();
        nin = new javax.swing.JTextField();
        sor = new javax.swing.JTextField();
        number_2 = new javax.swing.JTextField();
        kin = new javax.swing.JTextField();
        number = new javax.swing.JTextField();
        kin_no = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        conpass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Rampart One", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Registration Page ");

        jLabel2.setFont(new java.awt.Font("Rajdhani", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText(" Fill in this form with your acredited details ");

        other.setBackground(new java.awt.Color(0, 0, 0));
        other.setFont(new java.awt.Font("Rajdhani", 0, 14)); // NOI18N
        other.setText(" Other names : ");
        other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherActionPerformed(evt);
            }
        });

        firstname.setBackground(new java.awt.Color(0, 0, 0));
        firstname.setFont(new java.awt.Font("Rajdhani", 0, 14)); // NOI18N
        firstname.setText(" First Name : ");

        lastname.setBackground(new java.awt.Color(0, 0, 0));
        lastname.setFont(new java.awt.Font("Rajdhani", 0, 14)); // NOI18N
        lastname.setText(" Last Name :");

        bvn.setBackground(new java.awt.Color(0, 0, 0));
        bvn.setFont(new java.awt.Font("Rajdhani", 0, 14)); // NOI18N
        bvn.setText(" BVN :");
        bvn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bvnActionPerformed(evt);
            }
        });

        nin.setBackground(new java.awt.Color(0, 0, 0));
        nin.setFont(new java.awt.Font("Rajdhani", 0, 14)); // NOI18N
        nin.setText(" NIN :");
        nin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ninActionPerformed(evt);
            }
        });

        sor.setBackground(new java.awt.Color(0, 0, 0));
        sor.setFont(new java.awt.Font("Rajdhani", 0, 14)); // NOI18N
        sor.setText(" State of Origin :");
        sor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sorActionPerformed(evt);
            }
        });

        number_2.setBackground(new java.awt.Color(0, 0, 0));
        number_2.setFont(new java.awt.Font("Rajdhani", 0, 14)); // NOI18N
        number_2.setText(" other Phone No :");
        number_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number_2ActionPerformed(evt);
            }
        });

        kin.setBackground(new java.awt.Color(0, 0, 0));
        kin.setFont(new java.awt.Font("Rajdhani", 0, 14)); // NOI18N
        kin.setText(" Next of Kin :");
        kin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kinActionPerformed(evt);
            }
        });

        number.setBackground(new java.awt.Color(0, 0, 0));
        number.setFont(new java.awt.Font("Rajdhani", 0, 14)); // NOI18N
        number.setText("Phone No :");
        number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberActionPerformed(evt);
            }
        });

        kin_no.setBackground(new java.awt.Color(0, 0, 0));
        kin_no.setFont(new java.awt.Font("Rajdhani", 0, 14)); // NOI18N
        kin_no.setText(" Next of kin No :");
        kin_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kin_noActionPerformed(evt);
            }
        });

        pass.setBackground(new java.awt.Color(0, 0, 0));
        pass.setFont(new java.awt.Font("Rajdhani", 0, 14)); // NOI18N
        pass.setText("jPasswordField1");

        conpass.setBackground(new java.awt.Color(0, 0, 0));
        conpass.setFont(new java.awt.Font("Rajdhani", 0, 14)); // NOI18N
        conpass.setText("jPasswordField2");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Register");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Rajdhani", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Designed by Bakrin Daniel-23010301023");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(154, 154, 154))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(other)
                                .addComponent(kin)
                                .addComponent(number_2)
                                .addComponent(number)
                                .addComponent(bvn)
                                .addComponent(nin)
                                .addComponent(sor)
                                .addComponent(firstname)
                                .addComponent(lastname)
                                .addComponent(conpass)
                                .addComponent(pass)
                                .addComponent(kin_no, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(93, 93, 93)))))
                .addGap(28, 81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(other, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bvn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(conpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(number_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kin_no, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void otherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherActionPerformed

    private void bvnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bvnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bvnActionPerformed

    private void ninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ninActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ninActionPerformed

    private void sorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sorActionPerformed

    private void number_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_number_2ActionPerformed

    private void kinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kinActionPerformed

    private void numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberActionPerformed

    private void kin_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kin_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kin_noActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String fullname = firstname.getText().trim()+"  "+other.getText().trim()+" "+lastname.getText().trim();
     String  password = String.valueOf(pass.getPassword());
       String  conpassword = String.valueOf(conpass.getPassword());
       if(password.equals(conpassword)){
           try{
                  String connectionUrl = "jdbc:derby:C:\\Users\\User\\Desktop\\GK\\Database\\bank;create=true";
                  Connection con = DriverManager.getConnection(connectionUrl);
                  String insertQuery = "INSERT INTO bank (fullname, sor, nin, bvn, password, number, number_2, kin, kin_no) " +
                         "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
                  PreparedStatement pstmt = con.prepareStatement(insertQuery);
                   pstmt.setString(1, fullname);
                  pstmt.setString(2,  sor.getText());
                   pstmt.setString(3, nin.getText());
                   pstmt.setString(4, bvn.getText());
                   pstmt.setString(5, conpassword);
                   pstmt.setString(6, number.getText() );
                  pstmt.setString(7, number_2.getText());
                  pstmt.setString(8, kin.getText());
                 pstmt.setString(9, kin_no.getText());

    int rowsInserted = pstmt.executeUpdate();

    if (rowsInserted > 0) {
        JOptionPane.showMessageDialog(this, "Data inserted successfully!");
    }


           }catch(SQLException e){
                 JOptionPane.showMessageDialog(this, "this is not working");
                 e.printStackTrace();
           }
       }
       else{
           JOptionPane.showMessageDialog(this, "password does not match");
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bvn;
    private javax.swing.JPasswordField conpass;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kin;
    private javax.swing.JTextField kin_no;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField nin;
    private javax.swing.JTextField number;
    private javax.swing.JTextField number_2;
    private javax.swing.JTextField other;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField sor;
    // End of variables declaration//GEN-END:variables
}
